apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: roboshop
spec:
  clusterIP: LoadBalancer
    selector:
    app: nginx
    tier: db
    project: roboshop
  ports:
  - name: nginx-port
    protocol: TCP
    port: {{.values.service.port}} # this port belongs to service
    targetPort: http-web-svc #thi is belongs to container 

    